### PR TITLE
Added Word_en.yml

### PR DESCRIPTION
**Pull request by Elric02**
To fix blocks named "air" on /jobs info [job] 
I changed all blocks named "air" to their real names

### CODE REVIEW

**Comment by montlikadani** [comment]
This is not a fix for materials are named with air. If you using oldest minecraft version of your server then some materials and **some IDs are missing** so it will cause this showing air. We can't fix this issue because the Mojang don't release IDs to the materials where is missing. Changing the configs not fix this issue.

**Comment by Elric02** [comment]
I didn't fully understand this, but I can tell you surely that it worked for me. A lot of materials were showing "air" in /jobs info [job] AND in the Word_en.yml. So I just replaced all the "air" names by their real names in the Word_en.yml and it worked.

**Comment by montlikadani** [comment]
Yes, because you just renamed them, but it won't do anything for the job. This change is only for names and not for proper operation. If you try to do something about the job with a changed material, it will not gain income.

**Comment by Elric02** [comment]
Yes that's the problem I (and many others as I understood) experienced, blocks are working fine but names were showing "air" in the /jobs info. So that's why I corrected Word_en.yml, so that now /jobs info shows correct blocks and items instead of "air"

**Pull request closed without merging**
