### PR TITLE
Add compatibility with BlockTracker

### PR DESCRIPTION
**Pull request by flo0s**
I've just added a way to use the BlockTracker plugin (https://github.com/Krakenied/BlockTracker) to prevent players who just place and break blocks from winning the jobs rewards.

### CODE REVIEW

**Comment by Maxlego08** [comment]
love this !

**Comment by WarnDa** [comment]
Perfect PR !!

**Comment by totorocodesoften** [comment]
Could very well be a game changer. Awesome pr

**Comment by IbanEtchep** [comment]
Already exists
image

**Comment by WarnDa** [comment]
> Already exists image

This save block in a database, and only for some days, and it's heavier than this system that store blocks for months

**Pull request merged**
