### PR TITLE
#732 reward TIPPED_ARROW

### PR DESCRIPTION
**Pull request by kikelkik**
**Tipped Arrow**
Crafting a tipped arrow will be rewarded. 
Technically, there's no recipe provided for a tipped arrow by Spigot API , so I had to make it work this way. There will be made no difference by different effects of the tipped arrow.

**Lingering Potion**
Brewing a lingering potion cannot be rewarded, because Jobs can only reward the ingredients. 
Dragon's Breath already works fine, so you get rewarded when brewing lingering potions.

### CODE REVIEW

**Comment by montlikadani** [comment]
You would have to work on this to make it work properly. The following should be done:
- We should create a new enum in which we put all the Arrow, Potion and Lingering effects so we can work with different effects, not all of them.
- We should revisit the CRAFT action, in which we would put the effects as well as accept materials. but we do not do this, instead you can create a new Action in which we will include all the effects we want.
- There is no need to deal with recipes, because we do not make unique materials.

That would be a lot of work to do. We used to start with Potion effects, but there was a problem with it and it was removed, it will be added later.

Unfortunately, hard and time consuming work is required to work properly. You can use the Minecraft Official Website to find the appropriate effects ID as well as names. https://minecraft.gamepedia.com/Arrow

If you can’t do it, then this PR will stay open until someone (or we) add it.

**Comment by kikelkik** [comment]
Okay right if we want to respect potion types, there will be a lot more to do.

- I could create a new enum for all effects (Arrow, Potion and Lingering use the same effects).
- For that rework of the CRAFT action: We could delegate the PotionType of that item to a new constructor for ItemActionInfo. 
Then, I think there have to be changes made in the action method in Jobs,java, where the ActionInfo is passed to. 
But could you give me a hint where in this huge method body the actual Material of the ActionInfo is evaluated? It might be the same place where we have to add a check for that potion.
Or more general: Where does the plugin match a Material to the specified action?

**Comment by montlikadani** [comment]
You don't have to do any changes to the Jobs#action method and with ItemActionInfo. Just you have to use this method:
```java
Jobs.action(jPlayer, new ItemActionInfo(resultStack, ActionType.CRAFT));
```
`resultStack` is always be the crafted item when the player do that.

If you see `job#getJobInfo(info, level)` method you will see that the material/entity... stuffs are been translated by the TranslatableWords file.

**Comment by kikelkik** [comment]
Job#getJobInfo compares just names of material, but no ItemMeta. If we want to check e.g. a tipped_arrow + slowness, the item cannot simply be identified by it internal ID, because there are no sub-IDs for potion stuff, just NBT Tags (ItemMeta). 

So you mean I have to make these changes in `getJobInfo(action, level)` by expanding it with a ItemMeta check? But then, an ActionInfo has to have a field for itemMeta or potion effect in order to compare it with the actual JobInfo, or shall it be represented as a subType?

**Comment by montlikadani** [comment]
> So you mean I have to make these changes in `getJobInfo(action, level)` by expanding it with a ItemMeta check? But then, an ActionInfo has to have a field for itemMeta or potion effect in order to compare it with the actual JobInfo, or shall it be represented as a subType?

No, you have to put the ItemMeta checks in another static method (like Util) or making a new class, extending with `BaseActionInfo` in `actions` package to check the ItemMeta for effects.

**Comment by montlikadani** [comment]
Is there any progress on this?

**Comment by kikelkik** [comment]
Hey, I just continued working on it and saw that you already merged it. However, I've not been finished in that moment. 

I just corrected most of Potion names.

And I've got an open question:
I didn't get to implement that correct translation for material with potions.
Example in jobConfig: TIPPED_ARROW-SLOWNESS
Works fine but in /jobs info the correct name doesn't show up - its just "None".

I think it shouldn't be much work. So because you already know how this works, could you do that translating thing?

**Comment by montlikadani** [comment]
I'm sorry I accepted soon. I just didn't think ahead. Open another PR.

I think `/jobs info` only displays the items that are in the CMIMaterial enum.

**Pull request merged**
