### PR TITLE
Bucketing Entities Action

### PR DESCRIPTION
**Pull request by FireML**
Adds a new action type called "Bucket", which will payout when an aquatic entity is bucketed.

### CODE REVIEW

**Comment by FireML** [comment]
Any information on this @Zrips? It's been a while since I made it

**Comment by Zrips** [comment]
Can't merge this one directly as its not properly version dependent. Bucketing entities is relatively new event, it needs to be moved into its correct separate event listener which gets enabled past certain minecraft version.

**Comment by FireML** [comment]
I see. I'll sort that out soonish

**Comment by FireML** [comment]
Sorted

**Pull request merged**
